'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useVillageTheme } from '@/lib/theme/useVillageTheme';
import { BankBottomNav } from '../page';

const B = {
  day:   { bg:'#F2F7FA', card:'#FFFFFF', border:'#C8DCE8', text:'#0A1F2E', textSec:'#3A5A6E', textTer:'#7A9AAE', action:'#0A5F8A' },
  night: { bg:'#060F18', card:'#0E1E2E', border:'#1A3040', text:'#EEF4F8', textSec:'#8EB4CC', textTer:'#4A7A96', action:'#2A9FCC' },
};

const MOCK_FUND = {
  name:    'Family Growth Fund',
  focus:   'Diversified ETFs + Real Estate',
  members: 4,
  aum:     24000,
  mtd:     2.8,
  ytd:     11.4,
  inception: 18.2,
  avatars: ['JA','NJ','MT','AB'],
  sparkline: [60,62,59,65,70,74,72,78,80,82,79,85,88,84,90,92,89,95,93,100],
};

export default function VillageFundPage() {
  const { theme } = useVillageTheme();
  const isNight = theme === 'night';
  const c = isNight ? B.night : B.day;

  const sparkH = 36;
  const sparkW = 140;
  const max = Math.max(...MOCK_FUND.sparkline);
  const pts = MOCK_FUND.sparkline.map((v,i)=>`${(i/(MOCK_FUND.sparkline.length-1))*sparkW},${sparkH-(v/max)*sparkH}`).join(' ');

  return (
    <div style={{ background:c.bg, minHeight:'100vh', maxWidth:480, margin:'0 auto', paddingBottom:88 }}>
      {/* Top bar */}
      <div style={{ display:'flex', alignItems:'center', justifyContent:'space-between', padding:'16px 20px 12px', background:c.card, borderBottom:`1px solid ${c.border}` }}>
        <div style={{ display:'flex', alignItems:'center', gap:12 }}>
          <Link href="/village/bank" style={{ color:c.action, lineHeight:0 }}>
            <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><path d="M19 12H5M12 19l-7-7 7-7"/></svg>
          </Link>
          <span style={{ fontWeight:800, fontSize:17, color:c.text }}>Village Fund</span>
        </div>
        <button style={{ width:32, height:32, borderRadius:'50%', background:c.action, border:'none', display:'flex', alignItems:'center', justifyContent:'center', cursor:'pointer' }}>
          <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="#fff" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>
        </button>
      </div>

      <div style={{ padding:16 }}>
        {/* Compliance banner */}
        <div style={{ background:'#EAF3DE', border:'1px solid #639922', borderRadius:12, padding:'10px 14px', marginBottom:16 }}>
          <div style={{ display:'flex', alignItems:'flex-start', gap:8 }}>
            <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="#27500A" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" style={{ marginTop:1, flexShrink:0 }}><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"/></svg>
            <div>
              <p style={{ fontSize:11, color:'#27500A', margin:'0 0 4px', fontWeight:700 }}>Compliance Notice</p>
              <p style={{ fontSize:11, color:'#27500A', margin:0, lineHeight:1.5 }}>
                Village Funds operate under <strong>Reg D (506b)</strong> private placement exemption. Structured as Delaware LLCs via Stripe Atlas. 
                Legal docs generated by <strong>OpenLaw</strong>, signed via <strong>DocuSeal</strong>. 
                Smart contracts deployed on <strong>Polygon</strong> blockchain for immutable record-keeping.
                Not registered securities. Accredited investors only for funds exceeding $10M AUM.
              </p>
            </div>
          </div>
        </div>

        {/* Portfolio summary */}
        <div style={{ background:'#0A5F8A', borderRadius:20, padding:20, marginBottom:16, position:'relative', overflow:'hidden' }}>
          <div style={{ position:'absolute', top:-30, right:-30, width:130, height:130, borderRadius:'50%', background:'rgba(255,255,255,0.06)', pointerEvents:'none' }}/>
          <p style={{ color:'rgba(255,255,255,0.7)', fontSize:11, fontWeight:600, letterSpacing:0.8, textTransform:'uppercase', marginBottom:4, position:'relative' }}>Total Invested</p>
          <p style={{ color:'#fff', fontSize:32, fontWeight:800, letterSpacing:-1, margin:'0 0 4px', position:'relative' }}>$24,000.00</p>
          <p style={{ color:'rgba(255,255,255,0.8)', fontSize:13, position:'relative' }}><span style={{ color:'#7FFFD4', fontWeight:700 }}>+$672 (+2.8%)</span> this month</p>
          <div style={{ display:'flex', gap:20, marginTop:12, position:'relative' }}>
            <div><p style={{ color:'rgba(255,255,255,0.6)', fontSize:11, margin:0 }}>Active Funds</p><p style={{ color:'#fff', fontSize:16, fontWeight:700, margin:0 }}>1</p></div>
            <div><p style={{ color:'rgba(255,255,255,0.6)', fontSize:11, margin:0 }}>Members</p><p style={{ color:'#fff', fontSize:16, fontWeight:700, margin:0 }}>4</p></div>
            <div><p style={{ color:'rgba(255,255,255,0.6)', fontSize:11, margin:0 }}>YTD Return</p><p style={{ color:'#7FFFD4', fontSize:16, fontWeight:700, margin:0 }}>+11.4%</p></div>
          </div>
        </div>

        {/* Fund card */}
        <div style={{ background:c.card, border:`1px solid ${c.border}`, borderRadius:18, padding:16, marginBottom:16, overflow:'hidden' }}>
          <div style={{ display:'flex', justifyContent:'space-between', alignItems:'flex-start', marginBottom:12 }}>
            <div>
              <p style={{ fontSize:15, fontWeight:800, color:c.text, margin:0 }}>{MOCK_FUND.name}</p>
              <p style={{ fontSize:11, color:c.textTer, margin:'3px 0 0' }}>{MOCK_FUND.focus}</p>
            </div>
            <span style={{ fontSize:11, fontWeight:700, background:isNight?'#0D2A1E':'#ECFDF5', color:'#0F6E56', borderRadius:20, padding:'3px 10px' }}>Active</span>
          </div>

          {/* Member avatars */}
          <div style={{ display:'flex', alignItems:'center', gap:-8, marginBottom:14 }}>
            {MOCK_FUND.avatars.map((av,i)=>(
              <div key={av} style={{ width:32, height:32, borderRadius:'50%', background:c.action, border:`2px solid ${c.card}`, marginLeft:i>0?-8:0, display:'flex', alignItems:'center', justifyContent:'center', color:'#fff', fontSize:10, fontWeight:700, zIndex:MOCK_FUND.avatars.length-i }}>
                {av}
              </div>
            ))}
            <span style={{ fontSize:12, color:c.textSec, marginLeft:10 }}>{MOCK_FUND.members} members</span>
          </div>

          {/* Stats grid */}
          <div style={{ display:'grid', gridTemplateColumns:'repeat(3,1fr)', gap:8, marginBottom:14 }}>
            {[
              { label:'AUM', value:`$${MOCK_FUND.aum.toLocaleString()}` },
              { label:'MTD', value:`+${MOCK_FUND.mtd}%` },
              { label:'YTD', value:`+${MOCK_FUND.ytd}%` },
            ].map(s=>(
              <div key={s.label} style={{ background:isNight?'#1A3040':'#F2F7FA', borderRadius:10, padding:'10px 8px', textAlign:'center' }}>
                <p style={{ fontSize:11, color:c.textTer, margin:'0 0 2px' }}>{s.label}</p>
                <p style={{ fontSize:14, fontWeight:800, color:s.label!=='AUM'?'#0F6E56':c.text, margin:0 }}>{s.value}</p>
              </div>
            ))}
          </div>

          {/* Sparkline */}
          <div style={{ marginBottom:14 }}>
            <svg viewBox={`0 0 ${sparkW} ${sparkH}`} width="100%" height={sparkH} preserveAspectRatio="none">
              <defs>
                <linearGradient id="fundGrad" x1="0" y1="0" x2="0" y2="1">
                  <stop offset="0%" stopColor={c.action} stopOpacity="0.3"/>
                  <stop offset="100%" stopColor={c.action} stopOpacity="0"/>
                </linearGradient>
              </defs>
              <polygon points={`0,${sparkH} ${pts} ${sparkW},${sparkH}`} fill="url(#fundGrad)"/>
              <polyline points={pts} fill="none" stroke={c.action} strokeWidth="1.5" strokeLinejoin="round"/>
            </svg>
          </div>

          {/* Actions */}
          <div style={{ display:'flex', gap:8 }}>
            {['Contribute','Vote','Distributions'].map(action=>(
              <button key={action} style={{ flex:1, padding:'10px 0', borderRadius:10, border:`1px solid ${action==='Contribute'?'transparent':c.border}`, background:action==='Contribute'?c.action:'transparent', color:action==='Contribute'?'#fff':c.textSec, fontSize:11, fontWeight:700, cursor:'pointer' }}>
                {action}
              </button>
            ))}
          </div>
        </div>

        {/* Create fund CTA */}
        <button style={{ width:'100%', border:`2px dashed ${c.border}`, borderRadius:16, padding:'18px 0', background:'transparent', color:c.action, fontSize:14, fontWeight:700, cursor:'pointer', display:'flex', alignItems:'center', justifyContent:'center', gap:8 }}>
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"><path d="M12 5v14M5 12h14"/></svg>
          Create a Village Fund
        </button>
      </div>
      <BankBottomNav active="/village/bank/village-fund"/>
    </div>
  );
}
