-- GPS action ordering: lets Spirit/the goal generator mark an action as safe to
-- complete out of sequence (canRunInParallel) and declare which other actions
-- it depends on. Previously this was generated by lib/claude/gps.ts but written
-- to a non-existent `metadata` column on sprint_actions and silently dropped.

ALTER TABLE sprint_actions
  ADD COLUMN IF NOT EXISTS can_run_parallel     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS depends_on_action_ids UUID[] NOT NULL DEFAULT '{}',
  ADD COLUMN IF NOT EXISTS description           TEXT;

ALTER TABLE goal_steps
  ADD COLUMN IF NOT EXISTS can_run_parallel     BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS depends_on_step_ids   UUID[] NOT NULL DEFAULT '{}';
